### ISSUE TITLE
Develop or adapt dashboard and alerts.

### ISSUE THREAD

**Issue by xavier506** [edenia/tikuna#41]
Use grafana  /prometheus (or possibly custom graphQL API ) to create a  table of validator nodes showing malicious actors sorted by severity , based on a points system that indicates  number of problems detected. Similar to https://www.certik.com/

![Image](https://user-images.githubusercontent.com/5632966/188919314-748ed11d-290f-4987-bc9e-fec48ef14ab8.png)

## Tasks
- [ ] UI / UX design 
- [ ] Develop a UI for displaying results of analysis similar to [armiarma dashboard](https://migalabs.es/crawler/dashboard)
- [ ] Create a PR to add tikuna dashboards to [this repository](https://github.com/superphiz/dashboards)
