### ISSUE TITLE
Project Roadmap Content on website

### ISSUE THREAD

**Issue by xavier506** [edenia/tikuna#50]
Roadmap is on the project application document

- [ ] POC of ML Algorithm 

- [ ] Dashboard with data visualization 

- [ ] Publishing of Research Paper
